# Development version of configuration

# Database connection
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

# JPA and Hibernate configuration
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

security:
  jwt:
    secret: ${JWT_SECRET}
    issuer: ${JWT_ISSUER}
    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS}
    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME}
    cookie-secure: ${JWT_COOKIE_SECURE}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE}
    cookie-domain: ${JWT_COOKIE_DOMAIN}